### ISSUE TITLE
pretrained models

### ISSUE THREAD

**Issue by kaishijeng** [delftrobotics/keras-retinanet#6] opened 2017-09-21 00:07 UTC
Can you share pretrained models?
I like to check performance between retinanet and SSD.

Thanks,

**Comment by hgaiser** [comment] 2017-09-21 09:30
The plan is to train on COCO and upload that model somewhere public when RetinaNet is in a finished state. Right now I am still tweaking and tuning the model, it changes almost every day :)

Ideally the mAP for several datasets (VOC/COCO/?) will also be placed on the README.md. I am also curious if this implementation achieves similar results as the paper it is based on.

I hope that answers your question.

**Comment by hgaiser** [comment] 2017-09-25 06:59
FYI I am currently training on COCO and intending to release that model when it is done (might take a couple of days).

**Comment by hgaiser** [comment] 2017-10-16 20:31
Reopening as this still has to be addressed.

**Comment by hgaiser** [comment] 2017-11-01 10:04
Closing since pretrained COCO model has been made available on the [main page](https://github.com/delftrobotics/keras-retinanet/commit/9b5b3b1171871829682a6c0ed1c4ea1b7c12f657).

**Closed by hgaiser** 2017-11-01 10:04 UTC

**Comment by aleksanderserbin** [comment] 2017-11-13 12:52
@hgaiser, after 9760e65377d291b8f849166d7181a6fac5fa49e6 changes, pretrained model is no longer applicable.

**Comment by hgaiser** [comment] 2017-11-13 13:09
What is the error you are getting?

**Comment by aleksanderserbin** [comment] 2017-11-17 07:40
@hgaiser on loading weights I get the error that TensorReshape layer is unknown.
After rolling back to older version, it launches OK. Sorry, I am not able to get the detailed message right now and will post it here as soon as I can.


Can I use this model to train on my dataset? Is it correct that I will only have to retrain Classification net and Regression net, but not the ResNet?

**Comment by hgaiser** [comment] 2017-11-17 08:25
The architecture has changed, so the pretrained model has also changed. The updated link is in the README.md.

**Comment by aleksanderserbin** [comment] 2017-11-17 08:55
@hgaiser, thanks a lot.

Could you also validate this:
`Can I use this model to train on my dataset? Is it correct that I will only have to retrain Classification net and Regression net, but not the ResNet?`
